title:              BK SMKN 3 Cimahi
email:              rizkymaaa@gmail.com
description:        Yuk, Jadikan BK Sahabatmu
author:             author
baseurl:            ''
url:                https://bksahabatmu.xyz

# Social Profiles
twitter_username:  
github_username:  
facebook_username: "hilal.ckece.9"
instagram_username: "rizkymaaa"  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

collections:
  informasi:
    output: true
    permalink: /informasi/:path/

sass:
  sass_dir: _sass
  style: compressed
